defaults: &defaults
  uri: <%= uri = URI.parse(ENV['DOKKU_REDIS_URL'] || "redis://localhost:6379") %>
  host: <%= uri.host %>
  port: <%= uri.port %>

  <%# Redis doesn't use a username. The URL format (at least Dokku's) puts the password in the part of the URL parsed as the username. %>
  password: <%= uri.user %>

  db: 0
  cache_db: 2

development:
  <<: *defaults

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
